services:
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc
    ports:
      - "8042:8042"
      - "4242:4242"
    environment:
      VERBOSE_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"

      ORTHANC__NAME: "OrthancDemo"
      ORTHANC__REGISTERED_USERS: |
        {"orthanc":"orthanc"}
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"

      ORTHANC__OHIF__DATA_SOURCE: "dicom-web"
      ORTHANC__OHIF__ROUTER_BASENAME: "/ohif/"
    volumes:
      - ./orthanc-storage:/var/lib/orthanc/db
    restart: unless-stopped